import OpenAI from "openai";
import { NextResponse } from "next/server";
import { requireAuthenticatedUser } from "@/lib/api-auth";
import { rateLimitRequest } from "@/lib/rate-limit";

function normalizeCode(code?: string) {
  return code?.trim().toUpperCase() || "";
}

function fallbackReferralCode(userId: string, email?: string) {
  const handle = (email?.split("@")[0] || "USER").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 5);
  return `YIXI-${handle}${userId.replace(/-/g, "").slice(0, 5).toUpperCase()}`;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function buildPosterSvg({
  backgroundBase64,
  referralCode,
  inviteLink,
  isAi
}: {
  backgroundBase64?: string;
  referralCode: string;
  inviteLink: string;
  isAi: boolean;
}) {
  const safeCode = escapeXml(referralCode);
  const safeLink = escapeXml(inviteLink);
  const background = backgroundBase64
    ? `<image href="data:image/png;base64,${backgroundBase64}" x="0" y="0" width="1080" height="1350" preserveAspectRatio="xMidYMid slice"/>
       <rect width="1080" height="1350" fill="url(#veil)"/>`
    : `<rect width="1080" height="1350" fill="#F5FAFA"/>
       <circle cx="870" cy="220" r="230" fill="#9ED8DF" opacity="0.45"/>
       <circle cx="180" cy="1120" r="260" fill="#E8D4A8" opacity="0.34"/>
       <path d="M120 335 C280 210 450 205 650 290 S915 385 980 245" fill="none" stroke="#C79A54" stroke-width="3" opacity="0.22"/>
       <path d="M130 1040 C320 930 525 955 710 1090 S940 1190 995 1045" fill="none" stroke="#1495A0" stroke-width="4" opacity="0.16"/>
       <circle cx="540" cy="585" r="315" fill="none" stroke="#C79A54" stroke-width="2" opacity="0.25"/>
       <circle cx="540" cy="585" r="225" fill="none" stroke="#C79A54" stroke-width="2" opacity="0.16"/>
       <circle cx="540" cy="585" r="128" fill="none" stroke="#063F4A" stroke-width="2" opacity="0.1"/>`;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350">
    <defs>
      <linearGradient id="veil" x1="0" x2="1" y1="0" y2="1">
        <stop offset="0" stop-color="#F5FAFA" stop-opacity="0.12"/>
        <stop offset="0.5" stop-color="#063F4A" stop-opacity="0.08"/>
        <stop offset="1" stop-color="#102F38" stop-opacity="0.58"/>
      </linearGradient>
      <filter id="softShadow" x="-20%" y="-20%" width="140%" height="140%">
        <feDropShadow dx="0" dy="22" stdDeviation="22" flood-color="#102F38" flood-opacity="0.22"/>
      </filter>
    </defs>
    ${background}
    <rect x="66" y="66" width="948" height="1218" rx="54" fill="none" stroke="#E8D4A8" stroke-width="3" opacity="0.72"/>
    <rect x="106" y="102" width="868" height="1148" rx="40" fill="${isAi ? "#F5FAFA" : "#FFFFFF"}" opacity="${isAi ? "0.88" : "0.66"}"/>
    <text x="142" y="186" font-family="Arial, PingFang SC, sans-serif" font-size="30" font-weight="800" fill="#063F4A" letter-spacing="8">AI FENG SHUI MASTER</text>
    <text x="142" y="305" font-family="Arial, PingFang SC, sans-serif" font-size="76" font-weight="900" fill="#102F38">邀请你免费测算</text>
    <text x="142" y="380" font-family="Arial, PingFang SC, sans-serif" font-size="38" font-weight="700" fill="#6C8790">注册完成资料，双方各得 30 点</text>
    <rect x="142" y="472" width="796" height="238" rx="34" fill="#063F4A" filter="url(#softShadow)"/>
    <text x="194" y="558" font-family="Arial, PingFang SC, sans-serif" font-size="28" fill="#9ED8DF">专属推荐码</text>
    <text x="194" y="646" font-family="Arial, PingFang SC, sans-serif" font-size="64" font-weight="900" fill="#C79A54" letter-spacing="6">${safeCode}</text>
    <rect x="142" y="770" width="796" height="260" rx="34" fill="#FFFFFF" stroke="#E8D4A8" stroke-width="3"/>
    <text x="194" y="855" font-family="Arial, PingFang SC, sans-serif" font-size="35" font-weight="800" fill="#063F4A">用推荐链接注册</text>
    <text x="194" y="928" font-family="Arial, PingFang SC, sans-serif" font-size="28" fill="#6C8790">${safeLink}</text>
    <path d="M194 968 H886" stroke="#E8D4A8" stroke-width="3" opacity="0.7"/>
    <text x="194" y="1045" font-family="Arial, PingFang SC, sans-serif" font-size="30" font-weight="700" fill="#102F38">AI 给你速度，大师给你深度</text>
    <text x="194" y="1102" font-family="Arial, PingFang SC, sans-serif" font-size="25" fill="#6C8790">命理分析仅供参考，行动决定结果。</text>
    <text x="142" y="1208" font-family="Arial, PingFang SC, sans-serif" font-size="22" fill="#6C8790">${isAi ? "AI background generated by OpenAI. " : "Standard fallback poster. "}文字与推荐码由系统生成，确保准确。</text>
  </svg>`;
}

async function generateAiBackground() {
  if (!process.env.OPENAI_API_KEY) return undefined;

  const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const result = await client.images.generate({
    model: process.env.OPENAI_IMAGE_MODEL || "gpt-image-1.5",
    prompt:
      "Premium vertical referral poster background for a modern AI Feng Shui SaaS brand. Deep teal, jade teal, mist white, elegant gold, soft champagne, subtle luopan compass geometry, refined Chinese metaphysics mood, luxury technology, airy and clean, large empty space for overlay text, no readable text, no logo, no QR code, no watermark.",
    size: "1024x1536",
    output_format: "png",
    n: 1
  });

  return result.data?.[0]?.b64_json;
}

export async function POST(request: Request) {
  const limited = rateLimitRequest(request, { scope: "referral-poster", limit: 3, windowMs: 60_000 });

  if (limited) {
    return limited;
  }

  const { user, errorResponse } = await requireAuthenticatedUser(request);

  if (errorResponse || !user) {
    return errorResponse;
  }

  const origin = process.env.NEXT_PUBLIC_SITE_URL || new URL(request.url).origin;
  const referralCode = normalizeCode(user.user_metadata?.referral_code as string | undefined) || fallbackReferralCode(user.id, user.email);
  const inviteLink = `${origin}/auth?ref=${encodeURIComponent(referralCode)}`;

  try {
    const backgroundBase64 = await generateAiBackground();
    const posterSvg = buildPosterSvg({ backgroundBase64, referralCode, inviteLink, isAi: Boolean(backgroundBase64) });

    return NextResponse.json({
      posterSvg,
      fileName: `ai-referral-poster-${referralCode}.svg`,
      mode: backgroundBase64 ? "ai" : "fallback",
      message: backgroundBase64 ? "AI 推荐海报已生成。" : "未设置 OpenAI Image API，已生成标准海报。"
    });
  } catch (error) {
    const posterSvg = buildPosterSvg({ referralCode, inviteLink, isAi: false });
    return NextResponse.json({
      posterSvg,
      fileName: `ai-referral-poster-${referralCode}.svg`,
      mode: "fallback",
      message: error instanceof Error ? `AI 图片暂时不可用，已生成标准海报：${error.message}` : "AI 图片暂时不可用，已生成标准海报。"
    });
  }
}
